### ISSUE TITLE
1.1.0 Doesn't work with ES 0.90.3

### ISSUE THREAD

**Issue by hani** [yakaz/elasticsearch-action-updatebyquery#3]
Exception in thread "elasticsearch[node][bulk][T#1]" java.lang.NoSuchMethodError: org.elasticsearch.search.internal.SearchContext.<init>(JLorg/elasticsearch/search/internal/ShardSearchRequest;Lorg/elasticsearch/search/SearchShardTarget;Lorg/elasticsearch/index/engine/Engine$Searcher;Lorg/elasticsearch/index/service/IndexService;Lorg/elasticsearch/index/shard/service/IndexShard;Lorg/elasticsearch/script/ScriptService;)V
    at org.elasticsearch.action.updatebyquery.TransportShardUpdateByQueryAction.doExecuteInternal(TransportShardUpdateByQueryAction.java:139)
    at org.elasticsearch.action.updatebyquery.TransportShardUpdateByQueryAction.access$000(TransportShardUpdateByQueryAction.java:79)
    at org.elasticsearch.action.updatebyquery.TransportShardUpdateByQueryAction$1.run(TransportShardUpdateByQueryAction.java:127)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
